---
- name: Asynchronous task status
  hosts: webserver
  become: true
  tasks:
    - name: Downloading some big file
      get_url:
        url: https://download.virtualbox.org/virtualbox/5.2.18/VirtualBox-5.2-5.2.18_124319_el7-1.x86_64.rpm
        dest: /tmp/
      async: 20
      poll: 0
      register: download_sleeper
    - name: wait for download to finish
      async_status:
        jid: "{{ download_sleeper.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 1
