---
- name: Long running task
  hosts: webserver
  tasks:
    - name: download some big file
      get_url:
        url: https://download.virtualbox.org/virtualbox/5.2.18/VirtualBox-5.2-5.2.18_124319_el7-1.x86_64.rpm
        dest: /home/student/
      async: 1
      poll: 0
    - name: doing something
      command: ps
      register: output
    - name: displaying process data
      debug:
        msg: "{{ output }}"
