---
- name: Install httpd
  yum:
    name: httpd
    state: latest
- name: start httpd service
  service:
    name: httpd
    state: started
    enabled: true
- name: copy html content
  copy:
    src: html/
    dest: "/var/www/vhosts/{{ ansible_hostname }}"
- name: copy template vhost file
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify: restart httpd
